/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sledgely (https://sketchfab.com/Sledgely)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/labubu-fbe43a040f8b4c589c14509b23d40c78
Title: LABUBU
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { gsap } from 'gsap'

export function Labubu({ windowWidth, isOpen, ...props }) {
  const { nodes, materials } = useGLTF('/models/labubu.glb')
  const groupRef = useRef()
  const [isHovered, setIsHovered] = useState(false)

  const handleMouseEnter = () => {
        gsap.to(groupRef.current.position, {
            y: -window.innerHeight / 97,
            duration: windowWidth < 768 ? 1.5 : 1,
            ease: 'bounce.out',
            yoyo: true,
        })
        setTimeout(() => {
            setIsHovered(true)
        }, windowWidth < 768 ? 1500 : 1000)
  }


    useEffect(() => {
        if (isHovered) {
            gsap.to(groupRef.current.position, {
                y: groupRef.current.position.y - 0.5,
                duration: 1.5,
                ease: 'bounce.out',
                yoyo: true,
                repeat: -1,
              })
            setIsHovered(false)
        }
    },[isHovered])


  return (
    <group
      ref={groupRef}
      {...props}
      dispose={null}
      onPointerEnter={handleMouseEnter}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.NurbsPath}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.body}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.body_outline}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.ears}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.eyes}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.foot}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.hand}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.in_head}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.nose}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.tooth}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/labubu.glb')
