/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mfxmotions (https://sketchfab.com/mfxmotions)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rick-and-morty-laser-gun-free-3d-model-75fb5f27e46e4123ba6016185851f89b
Title: Rick And Morty Laser Gun Free 3D Model
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { gsap } from 'gsap'

export function Lazer(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/lazer.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const shoot = () => {
      gsap.to(group.current.rotation, {
        z: -Math.PI / 5, 
        duration: 1.5,
        yoyo: true,
        repeat: -1, // Repeat continuously
        ease: 'power1.inOut',
      })
    }
  
    shoot()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Empty_20" scale={[2.526, 2.526, 0.747]}>
                <group
                  name="Circle_5"
                  position={[-1.01, 0.268, 0]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={[0.21, 0.21, 0.709]}>
                  <mesh
                    name="Object_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.material}
                  />
                </group>
                <group name="Circle001_6" scale={[0.396, 0.396, 1.339]}>
                  <mesh
                    name="Object_7"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials['Material.001']}
                  />
                  <mesh
                    name="Object_8"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials.Golg}
                  />
                </group>
                <group name="Cube_7" position={[0.444, 0.605, 0]} scale={[0.183, 0.075, 0.393]}>
                  <mesh
                    name="Object_10"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_10.geometry}
                    material={materials.Green_Blue}
                  />
                </group>
                <group name="Cube001_8" position={[-0.2, 0.541, 0]} scale={[0.131, 0.046, 0.327]}>
                  <mesh
                    name="Object_12"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_12.geometry}
                    material={materials.Green_Blue}
                  />
                </group>
                <group name="Cube002_9" position={[0.73, 0.483, 0]} scale={[0.032, 0.041, 0.203]}>
                  <mesh
                    name="Object_14"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials.Golg}
                  />
                </group>
                <group
                  name="Cylinder_10"
                  position={[-0.243, 0.268, 0]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={[0.203, 0.203, 0.686]}>
                  <mesh
                    name="Object_16"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_16.geometry}
                    material={materials.Silver}
                  />
                  <mesh
                    name="Object_17"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials.Main_Body}
                  />
                  <mesh
                    name="Object_18"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_18.geometry}
                    material={materials['Material.003']}
                  />
                </group>
                <group
                  name="Cylinder001_11"
                  position={[-0.792, 0.264, 0]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={[0.127, 0.017, 0.43]}>
                  <mesh
                    name="Object_20"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_20.geometry}
                    material={materials.material}
                  />
                </group>
                <group name="Cylinder002_12" scale={[0.396, 0.396, 1.339]}>
                  <mesh
                    name="Object_22"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_22.geometry}
                    material={materials.Green_Blue}
                  />
                </group>
                <group
                  name="Cylinder003_13"
                  position={[0.178, 0.589, 0]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={[0.039, 0.068, 0.132]}>
                  <mesh
                    name="Object_24"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_24.geometry}
                    material={materials.Glow}
                  />
                  <mesh
                    name="Object_25"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_25.geometry}
                    material={materials.Green_Blue}
                  />
                </group>
                <group
                  name="Plane_14"
                  position={[0.595, -0.351, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.252, 0.853, 0.252]}>
                  <mesh
                    name="Object_27"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_27.geometry}
                    material={materials.Main_Body}
                  />
                </group>
                <group
                  name="Plane001_15"
                  position={[0.163, 0.026, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.04, 0.137, 0.04]}>
                  <mesh
                    name="Object_29"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_29.geometry}
                    material={materials['Material.003']}
                  />
                </group>
                <group
                  name="Plane002_16"
                  position={[-0.149, -0.032, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={[0.047, 0.266, 0.047]}>
                  <mesh
                    name="Object_31"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_31.geometry}
                    material={materials.Main_Body}
                  />
                </group>
                <group name="Plane004_18" scale={[0.396, 0.396, 1.339]}>
                  <mesh
                    name="Object_33"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_33.geometry}
                    material={materials.Green_Blue}
                  />
                </group>
                <group name="Plane005_19" scale={[0.396, 0.396, 1.339]}>
                  <mesh
                    name="Object_35"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_35.geometry}
                    material={materials['Material.003']}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/lazer.glb')
